spring.application.name=Sistema de vendas

spring.datasource.url=jdbc:postgresql://localhost:5432/vendas_db
spring.datasource.username=admin
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=V1pYd0VhT1hHcFhWQkJpRkZsV0xMZ0dXb3JzZ3lR
jwt.expiration=86400000